// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RealState.Infrastructure.SQLDataAccess.Entities
{
    public partial class Owner
    {
        public Owner()
        {
            Property = new HashSet<Property>();
        }

        [Key]
        public Guid IdOwner { get; set; }
        [Required]
        [StringLength(200)]
        public string Name { get; set; }
        [Required]
        [StringLength(80)]
        public string FirstSurname { get; set; }
        [Required]
        [StringLength(80)]
        public string SecondSurname { get; set; }
        [Required]
        [StringLength(300)]
        public string Address { get; set; }
        [Required]
        public byte[] Photo { get; set; }
        [Column(TypeName = "date")]
        public DateTime Birthday { get; set; }

        [InverseProperty("IdOwnerNavigation")]
        public virtual ICollection<Property> Property { get; set; }
    }
}