// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RealState.Infrastructure.SQLDataAccess.Entities
{
    public partial class PropertyImage
    {
        [Key]
        public Guid IdPropertyImage { get; set; }
        public Guid IdProperty { get; set; }
        [Required]
        public byte[] File { get; set; }
        public bool? Enabled { get; set; }

        [ForeignKey(nameof(IdProperty))]
        [InverseProperty(nameof(Property.PropertyImage))]
        public virtual Property IdPropertyNavigation { get; set; }
    }
}