// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RealState.Infrastructure.SQLDataAccess.Entities
{
    public partial class Property
    {
        public Property()
        {
            PropertyImage = new HashSet<PropertyImage>();
            PropertyTrace = new HashSet<PropertyTrace>();
        }

        [Key]
        public Guid IdProperty { get; set; }
        [Required]
        [StringLength(250)]
        public string Name { get; set; }
        [Required]
        [StringLength(300)]
        public string Address { get; set; }
        [Column(TypeName = "decimal(19, 4)")]
        public decimal Price { get; set; }
        [Required]
        [StringLength(25)]
        public string CodeInternal { get; set; }
        [Column(TypeName = "date")]
        public DateTime Year { get; set; }
        public Guid IdOwner { get; set; }

        [ForeignKey(nameof(IdOwner))]
        [InverseProperty(nameof(Owner.Property))]
        public virtual Owner IdOwnerNavigation { get; set; }
        [InverseProperty("IdPropertyNavigation")]
        public virtual ICollection<PropertyImage> PropertyImage { get; set; }
        [InverseProperty("IdPropertyNavigation")]
        public virtual ICollection<PropertyTrace> PropertyTrace { get; set; }
    }
}