// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RealState.Infrastructure.SQLDataAccess.Entities
{
    public partial class PropertyTrace
    {
        [Key]
        public Guid IdPropertyTrace { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DateSale { get; set; }
        [Required]
        [StringLength(250)]
        public string Name { get; set; }
        [Required]
        [StringLength(250)]
        public string Value { get; set; }
        [Column(TypeName = "decimal(19, 4)")]
        public decimal Tax { get; set; }
        public Guid IdProperty { get; set; }

        [ForeignKey(nameof(IdProperty))]
        [InverseProperty(nameof(Property.PropertyTrace))]
        public virtual Property IdPropertyNavigation { get; set; }
    }
}